export enum Character {
  CAPTAIN_FALCON = 0,
  DONKEY_KONG = 1,
  FOX = 2,
  GAME_AND_WATCH = 3,
  KIRBY = 4,
  BOWSER = 5,
  LINK = 6,
  LUIGI = 7,
  MARIO = 8,
  MARTH = 9,
  MEWTWO = 10,
  NESS = 11,
  PEACH = 12,
  PIKACHU = 13,
  ICE_CLIMBERS = 14,
  JIGGLYPUFF = 15,
  SAMUS = 16,
  YOSHI = 17,
  ZELDA = 18,
  SHEIK = 19,
  FALCO = 20,
  YOUNG_LINK = 21,
  DR_MARIO = 22,
  ROY = 23,
  PICHU = 24,
  GANONDORF = 25,
  MASTER_HAND = 26,
  WIREFRAME_MALE = 27,
  WIREFRAME_FEMALE = 28,
  GIGA_BOWSER = 29,
  CRAZY_HAND = 30,
  SANDBAG = 31,
  POPO = 32,
}

export const characterNames: Record<number, string> = {
  [Character.MARIO]: "Mario",
  [Character.FOX]: "Fox",
  [Character.CAPTAIN_FALCON]: "Captain Falcon",
  [Character.DONKEY_KONG]: "Donkey Kong",
  [Character.KIRBY]: "Kirby",
  [Character.BOWSER]: "Bowser",
  [Character.LINK]: "Link",
  [Character.SHEIK]: "Sheik",
  [Character.NESS]: "Ness",
  [Character.PEACH]: "Peach",
  [Character.POPO]: "Popo",
  [Character.PIKACHU]: "Pikachu",
  [Character.SAMUS]: "Samus",
  [Character.YOSHI]: "Yoshi",
  [Character.JIGGLYPUFF]: "Jigglypuff",
  [Character.MEWTWO]: "Mewtwo",
  [Character.LUIGI]: "Luigi",
  [Character.MARTH]: "Marth",
  [Character.ZELDA]: "Zelda",
  [Character.YOUNG_LINK]: "Young Link",
  [Character.DR_MARIO]: "Dr. Mario",
  [Character.FALCO]: "Falco",
  [Character.PICHU]: "Pichu",
  [Character.GAME_AND_WATCH]: "Mr. Game & Watch",
  [Character.GANONDORF]: "Ganondorf",
  [Character.ROY]: "Roy",
  [Character.MASTER_HAND]: "Master Hand",
  [Character.WIREFRAME_MALE]: "Wireframe Male",
  [Character.WIREFRAME_FEMALE]: "Wireframe Female",
  [Character.GIGA_BOWSER]: "Giga Bowser",
  [Character.SANDBAG]: "Sandbag",
};

export const characterShortNames: Record<number, string> = {
  [Character.MARIO]: "Mario",
  [Character.FOX]: "Fox",
  [Character.CAPTAIN_FALCON]: "Falcon",
  [Character.DONKEY_KONG]: "DK",
  [Character.KIRBY]: "Kirby",
  [Character.BOWSER]: "Bowser",
  [Character.LINK]: "Link",
  [Character.SHEIK]: "Sheik",
  [Character.NESS]: "Ness",
  [Character.PEACH]: "Peach",
  [Character.POPO]: "Popo",
  [Character.PIKACHU]: "Pikachu",
  [Character.SAMUS]: "Samus",
  [Character.YOSHI]: "Yoshi",
  [Character.JIGGLYPUFF]: "Puff",
  [Character.MEWTWO]: "Mewtwo",
  [Character.LUIGI]: "Luigi",
  [Character.MARTH]: "Marth",
  [Character.ZELDA]: "Zelda",
  [Character.YOUNG_LINK]: "Young Link",
  [Character.DR_MARIO]: "Dr. Mario",
  [Character.FALCO]: "Falco",
  [Character.PICHU]: "Pichu",
  [Character.GAME_AND_WATCH]: "G & W",
  [Character.GANONDORF]: "Ganon",
  [Character.ROY]: "Roy",
  [Character.MASTER_HAND]: "Master Hand",
  [Character.WIREFRAME_MALE]: "WF M",
  [Character.WIREFRAME_FEMALE]: "WF F",
  [Character.GIGA_BOWSER]: "Giga Bowser",
  [Character.SANDBAG]: "Sandbag",
};
